colorscheme = "cointop"

base_fg = "white"
base_bg = "gray"

chart_fg = "white"
chart_bg = "gray"
chart_bold = false

marketbar_fg = "white"
marketbar_bg = "gray"
marketbar_bold = false

marketbar_label_active_fg = "cyan"
marketbar_label_active_bg = "gray"
marketbar_label_active_bold = false

menu_fg = "white"
menu_bg = "gray"
menu_bold = false

menu_header_fg = "gray"
menu_header_bg = "green"
menu_header_bold = false

menu_label_fg = "yellow"
menu_label_bg = "gray"
menu_label_bold = false

menu_label_active_fg = "yellow"
menu_label_active_bg = "gray"
menu_label_active_bold = true

searchbar_fg = "white"
searchbar_bg = "gray"
searchbar_bold = false

statusbar_fg = "black"
statusbar_bg = "cyan"
statusbar_bold = true

table_column_price_fg = "cyan"
table_column_price_bg = "gray"
table_column_price_bold = false

table_column_change_fg = "white"
table_column_change_bg = "gray"
table_column_change_bold = false

table_column_change_down_fg = "red"
table_column_change_down_bg = "gray"
table_column_change_down_bold = false

table_column_change_up_fg = "green"
table_column_change_up_bg = "gray"
table_column_change_up_bold = false

table_header_fg = "black"
table_header_bg = "green"
table_header_bold = true

table_header_column_active_fg = "black"
table_header_column_active_bg = "cyan"
table_header_column_active_bold = true

table_row_fg = "white"
table_row_bg = "gray"
table_row_bold = false

table_row_active_fg = "black"
table_row_active_bg = "yellow"
table_row_active_bold = true


table_row_favorite_fg = "yellow"
table_row_favorite_bg = "gray"
table_row_favorite_bold = false
