colorscheme = "synthwave"

base_fg = "white"
base_bg = "black"

chart_fg = "magenta"
chart_bg = "black"
chart_bold = false

marketbar_fg = "cyan"
marketbar_bg = "black"
marketbar_bold = false

marketbar_label_active_fg = "magenta"
marketbar_label_active_bg = "black"
marketbar_label_active_bold = false

menu_fg = "white"
menu_bg = "black"
menu_bold = false

menu_header_fg = "black"
menu_header_bg = "magenta"
menu_header_bold = false

menu_label_fg = "cyan"
menu_label_bg = "black"
menu_label_bold = false

menu_label_active_fg = "magenta"
menu_label_active_bg = "black"
menu_label_active_bold = true

searchbar_fg = "white"
searchbar_bg = "black"
searchbar_bold = false

statusbar_fg = "magenta"
statusbar_bg = "black"
statusbar_bold = false

table_column_price_fg = "magenta"
table_column_price_bg = "black"
table_column_price_bold = false

table_column_change_fg = "white"
table_column_change_bg = "black"
table_column_change_bold = false

table_column_change_down_fg = "magenta"
table_column_change_down_bg = "black"
table_column_change_down_bold = false

table_column_change_up_fg = "cyan"
table_column_change_up_bg = "black"
table_column_change_up_bold = false

table_header_fg = "black"
table_header_bg = "cyan"
table_header_bold = false

table_header_column_active_fg = "black"
table_header_column_active_bg = "magenta"
table_header_column_active_bold = false

table_row_fg = "cyan"
table_row_bg = "black"
table_row_bold = false

table_row_active_fg = "black"
table_row_active_bg = "magenta"
table_row_active_bold = false

table_row_favorite_fg = "magenta"
table_row_favorite_bg = "black"
table_row_favorite_bold = false