IDE:
  mainWindow:
    detached: !QVariantMap
      documents-dock: ""
      help-dock: ""
      post-dock: ""
    geometry: AdnQywADAAAAAAHgAAAAFAAAA78AAAQjAAAB4QAAABUAAAO+AAAEIgAAAAAAAAAAB4AAAAHhAAAAFQAAA74AAAQi
    state: AAAA/wAAAAD9AAAAAgAAAAAAAAAAAAAAAPwCAAAAAfsAAAAcAGQAbwBjAHUAbQBlAG4AdABzAC0AZABvAGMAawAAAAAA/////wAAAF4A////AAAAAQAAAV4AAAPg/AIAAAAC+wAAABIAaABlAGwAcAAtAGQAbwBjAGsBAAAAFAAAAq0AAABMAP////sAAAASAHAAbwBzAHQALQBkAG8AYwBrAQAAAsIAAAEyAAAATAD///8AAAB/AAAD4AAAAAEAAAACAAAAAQAAAAL8AAAAAA==
  postWindow:
    lineWrap: false
  recentDocuments: !QVariantList
    []